apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse_otel
    isDefault: true
    jsonData:
      server: clickhouse
      port: 8123
      username: otel
      defaultDatabase: otel
      protocol: http
      dialTimeout: 10
      queryTimeout: 60
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
    editable: true
